---
title: "resources"
description: |
  a collection of other people's writings, tutorials, etc. that I find particularly helpful
output: 
  distill::distill_article:
    self_contained: false
    highlight: kate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

*currently under development* 

It's finally time for an upgraded notebook! I've been Slacking myself (and subsequently burying) links to resources for far too long, so my favorites will now live here. 

## r tools

## data viz

* [from Data to Viz](https://www.data-to-viz.com/), a choose-your-adventure-type experience for creating your best data visualizations

* [The Sessions College Color Calculator](https://www.sessions.edu/color-calculator/), for creating color palettes

## creating presentations

* Meet xaringan: Making slides in R Markdown, by Allison Hill. [slides](https://arm.rbind.io/slides/xaringan.html#1)

* Something I haven't yet tried out (but really want to) -- [Sharing Your `xaringan` Slides](https://www.garrickadenbuie.com/blog/sharing-xaringan-slides/), by Garrick Aden-Buie

## learning materials

* Ever feel like you need a pick-me-up while learning stats or a new R tool? Look no further than [Allison Horst's](https://twitter.com/allison_horst) [R & stats illustrations](https://github.com/allisonhorst/stats-illustrations), featuring the cutest and most educational fuzzy monsters you'll ever see!

* I'll preface this by saying that I do not know much at all about machine learning, but this was shared with our MEDS students on Slack and looks *awesome* -- [The Hitchhiker's Guide to Responsible Machine Learning](https://betaandbit.github.io/RML/), by Przemysław Biecek, Anna Kozak & Aleksander Zawada

* [Mastering Shiny](https://mastering-shiny.org/index.html), by Hadley Wickham 

## data science communities

* [R-Ladies Santa Barbara](https://www.meetup.com/rladies-santa-barbara/) and [R-Ladies Global](https://rladies.org/), which work to promote gender diversity in the R community
* [EcoDataScience](https://eco-data-science.github.io/), an environmental data science study group at UCSB
* [Southern California R Users](https://socalr.org/), an alliance of R user groups in Southern California
* [Santa Barbara Women in STEM](https://www.sbwomeninstem.org/), while not specifically data science-focused, this group holds some really great career and networking events, panels, flash talks, and more

## web accessibility

* [The A11Y Project](https://www.a11yproject.com/) is a community-driven effort to make digital content more accessible. I still have a long way to go in making my own website [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/) compliant -- the A11Y Project not only has a ton of great blog posts, but also WCAG compliance checklist that I will definitely be returning to over and over again.
* [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/), a color blindness simulator -- just upload a file and view your color palettes as they would appear under different types of color deficiencies

## misc.

* Discover new music to jam out to while you hack at [Every Noise at Once](https://everynoise.com/engenremap.html)