---
title: "talks & workshops"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<span style = 'font-size:90%;'>`r fontawesome::fa("chevron-right", fill = "#64605F", a11y = "sem")` **Teach Me How to Google**</span>  
<span style = 'font-size:80%;'>Sam Csik</span>  
<span style = 'font-size:80%; color:#88a2a5;'>*a talk on how to troubleshoot code and Google for helpful answers*</span>  
<span style = 'font-size:80%;'>Master of Technology Management Program, UCSB, January 2022 (invited talk)</span>  
<span style = 'font-size:80%;'>Master of Environmental Data Science Program, UCSB, October 2021</span>

<span style = 'font-size:70%;'>[`r fontawesome::fa("github-square", fill = "#64605F", a11y = "sem")` source code](https://github.com/UCSB-MEDS/teach-me-how-to-google), [`r fontawesome::fa("tv", fill = "#64605F", a11y = "sem")` slides](https://ucsb-meds.github.io/teach-me-how-to-google/#1), [`r fontawesome::fa("plus", fill = "#64605F", a11y = "sem")` slide adaptations for invited talks](https://samanthacsik.github.io/teach-me-how-to-google/)</span>

<span style = 'font-size:90%;'>`r fontawesome::fa("chevron-right", fill = "#64605F", a11y = "sem")` **Data Science with R & Python**</span>  
<span style = 'font-size:80%;'>Sam Csik, An Bui, Sean Helvey & Lars Mininni</span>  
<span style = 'font-size:80%; color:#88a2a5;'>*an R to Python (and vice versa) translation workshop where participants are encouraged to code along as we wrangle and visualize the same data using both languages*</span>  
<span style = 'font-size:80%;'>R-Ladies Santa Barbara x Central Coast Python Meetup, December 2021</span>  

<span style = 'font-size:70%;'>[`r fontawesome::fa("github-square", fill = "#64605F", a11y = "sem")` source code](https://github.com/samanthacsik/RLadiesSB-RvsPython), [`r fontawesome::fa("tv", fill = "#64605F", a11y = "sem")` slides](https://docs.google.com/presentation/d/1jXb8wbcP2f7flSfLMoX2gui70G67XRjftJRMLselOlE/edit?usp=sharing)</span>

<span style = 'font-size:90%;'>`r fontawesome::fa("chevron-right", fill = "#64605F", a11y = "sem")` **RStudio Tips & Tricks (and other keyboard shortcuts to make you a more efficient coder)**</span>  
<span style = 'font-size:80%;'>Sam Csik</span>  
<span style = 'font-size:80%; color:#88a2a5;'>*a talk on RStudio IDE tips & tricks and other keyboard shortcuts*</span>  
<span style = 'font-size:80%;'>Master of Environmental Data Science Program, UCSB, November 2021</span>

<span style = 'font-size:70%;'>[`r fontawesome::fa("github-square", fill = "#64605F", a11y = "sem")` source code](https://github.com/UCSB-MEDS/R-tips-and-tricks), [`r fontawesome::fa("tv", fill = "#64605F", a11y = "sem")` slides](https://ucsb-meds.github.io/R-tips-and-tricks/#1)</span>

<span style = 'font-size:90%;'>`r fontawesome::fa("chevron-right", fill = "#64605F", a11y = "sem")` **Writing data science-related blog posts for your personal website**</span>  
<span style = 'font-size:80%;'>Sam Csik</span>  
<span style = 'font-size:80%; color:#88a2a5;'>*an overview of writing data science-related blog posts for your personal website, with a focus on blogging using the {distill} package.*</span>  
<span style = 'font-size:80%;'>Master of Environmental Data Science Program, UCSB, September 2021</span>

<span style = 'font-size:70%;'>[`r fontawesome::fa("github-square", fill = "#64605F", a11y = "sem")` source code](https://github.com/UCSB-MEDS/writing-blogposts), [`r fontawesome::fa("tv", fill = "#64605F", a11y = "sem")` slides](https://ucsb-meds.github.io/writing-blogposts/#1), [`r fontawesome::fa("blog", fill = "#64605F", a11y = "sem")` blog post](https://samanthacsik.github.io/posts/2021-09-21-my-first-test-post/)</span>

<span style = 'font-size:90%;'>`r fontawesome::fa("chevron-right", fill = "#64605F", a11y = "sem")` **Customizing Your Personal Website with CSS**</span>  
<span style = 'font-size:80%;'>Sam Csik</span>  
<span style = 'font-size:80%; color:#88a2a5;'>*an intro to using CSS to customize {distill} websites*</span>   
<span style = 'font-size:80%;'>Master of Environmental Data Science Program, UCSB, August 2021</span>

<span style = 'font-size:70%;'>[`r fontawesome::fa("github-square", fill = "#64605F", a11y = "sem")` source code](https://github.com/UCSB-MEDS/customizing-websites-css), [`r fontawesome::fa("tv", fill = "#64605F", a11y = "sem")` slides](https://ucsb-meds.github.io/customizing-websites-css/#1)</span>

<span style = 'font-size:90%;'>`r fontawesome::fa("chevron-right", fill = "#64605F", a11y = "sem")` **Data Viz**</span>  
<span style = 'font-size:80%;'>Sam Csik, An Bui & Juliette Verstaen</span>   
<span style = 'font-size:80%; color:#88a2a5;'>*a code-along workshop to learn/review the basics of `{ggplot2}` and create three unique visualizations using `{palmerpenguins}` data*</span>   
<span style = 'font-size:80%;'>R-Ladies Santa Barbara Meetup, May 2019</span>

<span style = 'font-size:70%;'>[`r fontawesome::fa("github-square", fill = "#64605F", a11y = "sem")` source code](https://github.com/j-verstaen/RLadiesSB-Data-Viz-Pt1), [`r fontawesome::fa("tv", fill = "#64605F", a11y = "sem")` slides](https://docs.google.com/presentation/d/1sU2H89F5e409WpYilRqYAqu7DdXSAivccEa4y44xZ7c/edit?usp=sharing)</span>

<span style = 'font-size:90%;'>`r fontawesome::fa("chevron-right", fill = "#64605F", a11y = "sem")` **Intro to the tidyverse**</span>  
<span style = 'font-size:80%;'>Sam Csik & An Bui</span>   
<span style = 'font-size:80%; color:#88a2a5;'>*a code-along workshop to learn data wrangling and visualization techniques using `{tidyverse}` functions*</span>   
<span style = 'font-size:80%;'>R-Ladies Santa Barbara Meetup, May 2019</span>

<span style = 'font-size:70%;'>[`r fontawesome::fa("github-square", fill = "#64605F", a11y = "sem")` source code](https://github.com/samanthacsik/Intro-to-the-Tidyverse), [`r fontawesome::fa("markdown", fill = "#64605F", a11y = "sem")` knitted RMarkdown](https://rpubs.com/scsik/RladiesSB-intro-to-the-tidyverse)</span>
